services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    depends_on:
      - mysql
      - tensorflow-service

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production

  mysql:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql

  tensorflow-service:
    image: tensorflow/serving
    ports:
      - "8501:8501"
    volumes:
      - ./models:/models
    environment:
      - MODEL_NAME=my_model

volumes:
  db-data:
  models:
